apiVersion: apps/v1
kind: Deployment
metadata:
  name: fuebiapp-startpage
  namespace: fuebiapp
  labels:
    app: fuebiapp-startpage
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fuebiapp-startpage
  template:
    metadata:
      labels:
        app: fuebiapp-startpage
    spec:
      containers:
      - name: fuebiapp-startpage
        image: blacktr/fuebi-startpage:latest
        ports:
        - containerPort: 80
        imagePullPolicy: Always